name: Run JavaScript

on:
  push:
    branches:
      - angel
      - master

  pull_request:
    branches:
      - angel
      - master

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Run JavaScript File
        run: node intern.js
